#!/bin/bash
git clone https://github.com/jan-janssen/FitSNAP.git
cp -r FitSNAP/fitsnap3 /srv/conda/envs/notebook/lib/python3.9/site-packages/
cp -r FitSNAP/fitsnaprun /srv/conda/envs/notebook/lib/python3.9/site-packages/
rm -rf FitSNAP
